# -*- coding: utf-8 -*-
"""spam msg detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10PYsX9o7poBJ_5hY7Uv_xMwBmNDAfp_H
"""

"""
app.py - Single-file Spam/Email Classifier Web App (Flask)

How to run (Linux / Colab / Windows WSL / macOS):
1. Create a venv (recommended) and install requirements:
   pip install -r requirements.txt
   where requirements.txt contains:
     Flask==2.2.5
     scikit-learn==1.2.2
     pandas==2.1.2
     joblib==1.3.2
     matplotlib==3.8.1
     seaborn==0.12.2
     python-dotenv==1.0.0
     Werkzeug==2.2.3

   Or install inline:
   pip install flask scikit-learn pandas joblib matplotlib seaborn python-dotenv

2. Run:
   python app.py

3. Open http://127.0.0.0.1:5000 in your browser.

Notes:
- The app will look for 'model.joblib' and 'vectorizer.joblib' in the working directory. If not found,
  it downloads the public SMS dataset, trains the TF-IDF + Logistic Regression model, saves artifacts,
  and shows initial metrics.
- You can retrain by uploading a dataset CSV/TSV with columns: 'label' and 'message' (labels: ham/spam or 0/1).
- For exposing to the public, use ngrok or localtunnel (ngrok recommended):
    ngrok http 5000
  or install npx localtunnel --port 5000
"""

import os
import io
import re
import joblib
import time
import tempfile
import traceback
from threading import Thread

from flask import Flask, request, jsonify, render_template_string, send_file, redirect, url_for, flash
from werkzeug.utils import secure_filename

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score, classification_report, confusion_matrix, roc_auc_score, roc_curve
)

# ---------------------------
# Config
# ---------------------------
MODEL_PATH = "model.joblib"
VECTORIZER_PATH = "vectorizer.joblib"
ALLOWED_EXT = {'csv', 'tsv', 'txt'}
DEFAULT_DATA_URL = "https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv"

app = Flask(__name__)
app.secret_key = os.environ.get("FLASK_SECRET", "replace_this_with_random_secret")  # for flash messages

# In-memory placeholders
model = None
vectorizer = None
last_metrics = {}

# ---------------------------
# Utilities
# ---------------------------
def allowed_file(filename):
    ext = filename.rsplit('.', 1)[-1].lower() if '.' in filename else ''
    return ext in ALLOWED_EXT

def clean_message_series(s: pd.Series) -> pd.Series:
    # Basic cleaning: strip, lower, remove excessive whitespace
    s = s.astype(str).fillna("").str.strip()
    s = s.str.replace(r'\s+', ' ', regex=True)
    return s

def load_model_and_vectorizer():
    global model, vectorizer, last_metrics
    if os.path.exists(MODEL_PATH) and os.path.exists(VECTORIZER_PATH):
        try:
            model = joblib.load(MODEL_PATH)
            vectorizer = joblib.load(VECTORIZER_PATH)
            print("Loaded existing model and vectorizer.")
            return True
        except Exception as e:
            print("Failed to load artifacts:", e)
            traceback.print_exc()
            return False
    return False

def train_and_save(df, label_col='label', text_col='message', save=True):
    """
    Trains TF-IDF + LogisticRegression on df and optionally saves artifacts.
    df must have label and message columns.
    Accepts label values: 'ham'/'spam' or 0/1.
    Returns metrics dict.
    """
    global model, vectorizer, last_metrics

    df = df.copy()
    df[text_col] = clean_message_series(df[text_col])
    df = df[df[text_col] != ""].reset_index(drop=True)
    if df.empty:
        raise ValueError("Training dataset is empty after cleaning.")

    # Map labels to 0/1
    if df[label_col].dtype == object:
        df[label_col] = df[label_col].str.lower().map({'ham': 0, 'spam': 1}).fillna(df[label_col])
    df[label_col] = pd.to_numeric(df[label_col], errors='coerce')
    df = df[df[label_col].isin([0,1])].reset_index(drop=True)
    if df.empty:
        raise ValueError("No valid labels (0/1 or ham/spam) found in dataset.")

    X = df[text_col]
    y = df[label_col].astype(int)

    # Split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

    # Vectorize
    vectorizer = TfidfVectorizer(stop_words='english', max_features=7000, ngram_range=(1,2))
    X_train_vec = vectorizer.fit_transform(X_train)
    X_test_vec = vectorizer.transform(X_test)

    # Model
    model = LogisticRegression(max_iter=2000, solver='liblinear')
    model.fit(X_train_vec, y_train)

    # Predict
    y_pred = model.predict(X_test_vec)
    y_proba = model.predict_proba(X_test_vec)[:, 1]

    # Metrics
    acc = float(accuracy_score(y_test, y_pred))
    report = classification_report(y_test, y_pred, output_dict=True)
    cm = confusion_matrix(y_test, y_pred).tolist()
    try:
        roc_auc = float(roc_auc_score(y_test, y_proba))
    except Exception:
        roc_auc = None

    metrics = {
        "accuracy": acc,
        "roc_auc": roc_auc,
        "confusion_matrix": cm,
        "report": report
    }

    last_metrics = metrics

    # Save artifacts
    if save:
        joblib.dump(model, MODEL_PATH)
        joblib.dump(vectorizer, VECTORIZER_PATH)
        print(f"Saved model ({MODEL_PATH}) and vectorizer ({VECTORIZER_PATH}).")

    return metrics

def train_on_default_dataset():
    try:
        df = pd.read_csv(DEFAULT_DATA_URL, sep='\t', header=None, names=['label', 'message'])
        df['label'] = df['label'].astype(str)
        metrics = train_and_save(df, label_col='label', text_col='message', save=True)
        return metrics
    except Exception as e:
        print("Failed to train on default dataset:", e)
        traceback.print_exc()
        raise

def predict_text(text: str):
    """
    Returns (label_str, confidence_float)
    """
    global model, vectorizer
    if not model or not vectorizer:
        raise RuntimeError("Model not loaded")
    if not text or not isinstance(text, str) or text.strip() == "":
        return "Not Spam", 0.0
    Xv = vectorizer.transform([text])
    pred = int(model.predict(Xv)[0])
    proba = float(model.predict_proba(Xv)[0][1])
    return ("Spam" if pred == 1 else "Not Spam", proba)

# Auto-load model if available, else train on default dataset
if not load_model_and_vectorizer():
    print("No saved model found; training on default dataset. This may take a moment...")
    try:
        metrics = train_on_default_dataset()
        print("Initial training completed:", metrics)
    except Exception as e:
        print("Initial training failed:", e)

# ---------------------------
# HTML Template (single-page)
# ---------------------------
HTML = """
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Spam & Email Detector — Data Science App</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Bootstrap CDN -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <style>
    body { background: #f8fafc; }
    .card { box-shadow: 0 2px 10px rgba(0,0,0,0.03); }
    .small-muted { font-size: 0.9rem; color: #6c757d; }
    pre { white-space: pre-wrap; word-wrap: break-word; }
  </style>
</head>
<body>
<div class="container my-4">
  <div class="d-flex justify-content-between align-items-center mb-3">
    <h3>Spam & Email Detector</h3>
    <div><a class="btn btn-outline-secondary btn-sm" href="/download/model">Download Model</a></div>
  </div>

  <div class="row gy-3">
    <!-- Left column: Input & Predict -->
    <div class="col-md-6">
      <div class="card p-3">
        <h5>Classify text (SMS / Email)</h5>
        <p class="small-muted">Paste any message (SMS or email body) and click <b>Check</b>.</p>
        <textarea id="inputText" rows="7" class="form-control" placeholder="Paste your message here..."></textarea>
        <div class="mt-3 d-flex gap-2">
          <button class="btn btn-primary" onclick="checkText()">Check</button>
          <button class="btn btn-outline-secondary" onclick="pasteDemo()">Use Demo</button>
          <button class="btn btn-outline-danger" onclick="clearResult()">Clear</button>
        </div>
        <div id="resultArea" class="mt-3"></div>
      </div>

      <div class="card p-3 mt-3">
        <h6>Upload dataset to retrain</h6>
        <form id="uploadForm" enctype="multipart/form-data" method="post" action="/upload">
          <div class="mb-2">
            <input type="file" name="file" class="form-control" />
            <div class="form-text">CSV/TSV with columns: <code>label</code> and <code>message</code> (labels: ham/spam or 0/1).</div>
          </div>
          <button type="submit" class="btn btn-success">Upload & Retrain</button>
          <a class="btn btn-outline-secondary" href="/" onclick="event.preventDefault(); retrainDefault()">Retrain on default dataset</a>
        </form>
        <div id="uploadMsg" class="mt-2"></div>
      </div>
    </div>

    <!-- Right column: Metrics -->
    <div class="col-md-6">
      <div class="card p-3">
        <h6>Model Metrics</h6>
        <div id="metricsArea">
          <p class="small-muted">Accuracy, ROC AUC, confusion matrix and classification report are shown here after training or on demand.</p>
          <ul class="list-group" id="metricList">
            <li class="list-group-item">Accuracy: <b id="accVal">-</b></li>
            <li class="list-group-item">ROC AUC: <b id="rocVal">-</b></li>
          </ul>
          <canvas id="cmChart" height="200" class="mt-3"></canvas>
        </div>
      </div>

      <div class="card p-3 mt-3">
        <h6>Top spam-indicating features</h6>
        <div id="featuresArea" class="small-muted">
          <ol id="featureList"></ol>
        </div>
      </div>

      <div class="card p-3 mt-3">
        <h6>Tips</h6>
        <ul>
          <li>Model: TF-IDF (uni+bi-grams) + LogisticRegression.</li>
          <li>Use a larger, domain-specific dataset for best email classification performance.</li>
          <li>To expose publicly, run <code>ngrok http 5000</code> or <code>npx localtunnel --port 5000</code>.</li>
        </ul>
      </div>
    </div>
  </div>

  <footer class="mt-4 small text-muted">Built with Python, Flask, scikit-learn. Model artifacts saved on server for persistence.</footer>
</div>

<script>
async function checkText(){
  const text = document.getElementById('inputText').value.trim();
  if(!text){ alert('Please paste or type some text first.'); return; }
  const resDiv = document.getElementById('resultArea');
  resDiv.innerHTML = '<div class="spinner-border spinner-border-sm" role="status"></div> Checking...';

  try{
    const r = await fetch('/api/predict', {method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({message: text})});
    const data = await r.json();
    if(r.ok){
      const cls = data.prediction === 'Spam' ? 'text-danger' : 'text-success';
      resDiv.innerHTML = `<div class="${cls}"><b>${data.prediction}</b> — Confidence: ${(data.confidence*100).toFixed(2)}%</div>
                          <pre class="mt-2">${text}</pre>`;
    } else {
      resDiv.innerHTML = `<div class="text-danger">Error: ${data.error || r.statusText}</div>`;
    }
  } catch(e){
    resDiv.innerHTML = `<div class="text-danger">Request failed: ${e}</div>`;
  }
}

function pasteDemo(){
  const samples = [
    "Congratulations! You have won a prize. Click here to claim your reward: http://fake.link",
    "Hi team, please find attached the minutes of today's meeting and action items.",
    "Your account has suspicious activity. Verify now: http://phish.example"
  ];
  document.getElementById('inputText').value = samples[Math.floor(Math.random()*samples.length)];
}

function clearResult(){
  document.getElementById('inputText').value = '';
  document.getElementById('resultArea'].innerHTML = '';
}

// retrieve metrics on load
async function fetchMetrics(){
  const r = await fetch('/api/metrics');
  if(!r.ok) return;
  const data = await r.json();
  document.getElementById('accVal'].innerText = data.accuracy !== null ? (data.accuracy*100).toFixed(2)+'%' : '-';
  document.getElementById('rocVal'].innerText = data.roc_auc !== null ? (data.roc_auc).toFixed(3) : '-';
  // confusion matrix
  if(data.confusion_matrix){
    const cm = data.confusion_matrix;
    renderConfusionMatrix(cm);
  }
  if(data.top_features){
    const list = document.getElementById('featureList'];
    list.innerHTML = '';
    data.top_features.slice(0,20).forEach(f => {
      const li = document.createElement('li');
      li.innerText = `${f[0]} (${f[1].toFixed(3)})`;
      list.appendChild(li);
    });
  }
}

function renderConfusionMatrix(cm){
  // cm is [[tn, fp], [fn, tp]]
  const ctx = document.getElementById('cmChart'].getContext('2d');
  if(window.cmChart) window.cmChart.destroy();
  const data = {
    labels: ['Pred Ham','Pred Spam'],
    datasets: [{
      label: 'Ham/Spam counts',
      data: [cm[0][0], cm[0][1], cm[1][0], cm[1][1]],
      backgroundColor: ['#6c757d','#dc3545','#ffc107','#198754']
    }]
  };
  window.cmChart = new Chart(ctx, {
    type: 'bar',
    data: {
      labels: ['True Ham / Pred Ham','True Ham / Pred Spam','True Spam / Pred Ham','True Spam / Pred Spam'],
      datasets: [{data: [cm[0][0], cm[0][1], cm[1][0], cm[1][1]], backgroundColor: ['#6c757d','#dc3545','#ffc107','#198754']}]
    },
    options:{responsive:true, plugins:{legend:{display:false}}}
  });
}

async function retrainDefault(){
  if(!confirm('Retrain on default SMS dataset? This will overwrite the saved model.')) return;
  const resDiv = document.getElementById('uploadMsg'];
  resDiv.innerHTML = 'Retraining on default dataset...';
  const r = await fetch('/retrain_default', {method:'POST'});
  const data = await r.json();
  if(r.ok){
    resDiv.innerHTML = '<div class="text-success">Retraining complete.</div>';
    fetchMetrics();
  } else {
    resDiv.innerHTML = '<div class="text-danger">Error: '+(data.error||r.statusText)+'</div>';
  }
}

// On page load
fetchMetrics();
</script>

</body>
</html>
"""

# ---------------------------
# Flask routes
# ---------------------------

@app.route("/")
def index():
    return render_template_string(HTML)

@app.route("/api/predict", methods=["POST"])
def api_predict():
    try:
        payload = request.get_json(force=True)
        text = payload.get("message", "")
        label, conf = predict_text(text)
        return jsonify({"prediction": label, "confidence": conf})
    except Exception as e:
        return jsonify({"error": str(e), "trace": traceback.format_exc()}), 400

@app.route("/api/metrics", methods=["GET"])
def api_metrics():
    # Returns last_metrics and top features
    global last_metrics, model, vectorizer
    if not model or not vectorizer:
        return jsonify({"error": "Model not available"}), 400
    metrics = last_metrics.copy() if last_metrics else {}
    # Top features
    try:
        feat_names = vectorizer.get_feature_names_out()
        coefs = getattr(model, "coef_", None)
        top = []
        if coefs is not None:
            coef_arr = coefs[0]
            # top positive features for spam
            idx = np.argsort(coef_arr)[::-1][:100]
            for i in idx:
                top.append((feat_names[i], float(coef_arr[i])))
        metrics["top_features"] = top
    except Exception as e:
        metrics["top_features"] = []
    # Ensure JSON-serializable types
    metrics_serializable = {
        "accuracy": metrics.get("accuracy"),
        "roc_auc": metrics.get("roc_auc"),
        "confusion_matrix": metrics.get("confusion_matrix"),
        "report": metrics.get("report"),
        "top_features": metrics.get("top_features", [])[:50]
    }
    return jsonify(metrics_serializable)

@app.route("/upload", methods=["POST"])
def upload_and_retrain():
    """
    Expects a form file upload with key 'file'.
    Acceptable formats: CSV/TSV with columns label,message
    """
    try:
        if 'file' not in request.files:
            flash("No file part in the request", "danger")
            return redirect(url_for('index'))
        file = request.files['file']
        if file.filename == '':
            flash("No selected file", "danger")
            return redirect(url_for('index'))
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            contents = file.read()
            # detect delimiter by extension or sniff
            ext = filename.rsplit('.',1)[-1].lower()
            if ext == 'tsv':
                df = pd.read_csv(io.BytesIO(contents), sep='\t', header=None, names=['label','message']) if b'\t' in contents else pd.read_csv(io.BytesIO(contents), sep='\t')
            else:
                # try csv with header detection
                try:
                    df = pd.read_csv(io.BytesIO(contents))
                    if 'label' not in df.columns or 'message' not in df.columns:
                        # fallback to no-header csv
                        df = pd.read_csv(io.BytesIO(contents), header=None, names=['label','message'])
                except Exception:
                    df = pd.read_csv(io.BytesIO(contents), sep='\t', header=None, names=['label','message'])
            # Validate columns
            if not {'label','message'}.issubset(set(df.columns)):
                flash("Uploaded file must contain 'label' and 'message' columns", "danger")
                return redirect(url_for('index'))
            # Train (blocking; for big files consider background thread)
            metrics = train_and_save(df, label_col='label', text_col='message', save=True)
            flash(f"Retraining complete. Accuracy: {metrics.get('accuracy'):.3f}", "success")
            return redirect(url_for('index'))
        else:
            flash("Unsupported file type. Use CSV or TSV.", "danger")
            return redirect(url_for('index'))
    except Exception as e:
        traceback.print_exc()
        flash(f"Retrain failed: {e}", "danger")
        return redirect(url_for('index'))

@app.route("/retrain_default", methods=["POST"])
def retrain_default():
    try:
        metrics = train_on_default_dataset()
        return jsonify({"status": "ok", "accuracy": metrics.get("accuracy"), "roc_auc": metrics.get("roc_auc")})
    except Exception as e:
        return jsonify({"error": str(e), "trace": traceback.format_exc()}), 500

@app.route("/download/model")
def download_model():
    # returns a zip of model + vectorizer
    from zipfile import ZipFile
    buf = io.BytesIO()
    with ZipFile(buf, "w") as z:
        if os.path.exists(MODEL_PATH):
            z.write(MODEL_PATH)
        if os.path.exists(VECTORIZER_PATH):
            z.write(VECTORIZER_PATH)
    buf.seek(0)
    return send_file(buf, download_name="model_artifacts.zip", as_attachment=True)

# ---------------------------
# Run app
# ---------------------------
if __name__ == "__main__":
    # Stop the previous Flask thread if it exists
    if 'flask_thread' in globals() and flask_thread.is_alive():
        print("Stopping existing Flask thread...")
        # This is a simple way to signal the thread to stop.
        # We'll use a basic approach for demonstration.
        import os, signal
        os.kill(os.getpid(), signal.SIGINT) # Send interrupt signal
        time.sleep(2) # Add a small delay to ensure the port is released

    print("Starting Flask app on http://0.0.0.0:5000")
    # Bind to 0.0.0.0 to allow tunneling and remote access
    app.run(host="0.0.0.0", port=5000, debug=False)

!npm install -g localtunnel

from threading import Thread
Thread(target=lambda: app.run(host="0.0.0.0", port=5000)).start()